package jmouseable.jmouseable;

public enum Synchronization {

    MOUSE_AND_GRID_CENTER_UNSYNCHRONIZED,
    MOUSE_FOLLOWS_GRID_CENTER,
    MOUSE_FOLLOWS_GRID_CENTER_EXCEPT_WHEN_GRID_CREATED,
    GRID_CENTER_FOLLOWS_MOUSE

}
